server:
  port: 7777
spring:
  application:
    name: GOGOU-COMMON
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka/
