server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///mybatispluss
    username: root
    password: root
  application:
    name: GOGOU-PRODUCT
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka/