server:
  port: 7777
  max-http-header-size: 1048576
spring:
  application:
    name: GOGOU-COMMON
  data:
    elasticsearch:
      cluster-nodes: localhost:9300
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka/
