server:
  port: 8082
spring:
  application:
    name: GOGOU-PRODUCT
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka/